22-rails-validations/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# resources :tacos, only: [:index, :show, :new, :create]

resources :tacos

# get '/tacos' => "tacos#index"

end

22-rails-validations/app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :taco_ingredients
  has_many :tacos, through: :taco_ingredients
end

22-rails-validations/app/models/taco.rb
class Taco < ApplicationRecord
  has_many :taco_ingredients
  has_many :ingredients, through: :taco_ingredients

  validates :name, presence: :true
  # validates :name, uniqueness: {case_sensitive: false}
  validates :name, :uniqueness => {:case_sensitive => false}
  validates :ingredients, presence: :true
  validate :excludes_taco_from_taco_name

  def excludes_taco_from_taco_name
    if name.downcase.include?('taco')
      errors.add(:name, 'cannot include taco')
    end
  end


end

22-rails-validations/app/models/taco_ingredient.rb
class TacoIngredient < ApplicationRecord
  belongs_to :taco
  belongs_to :ingredient
end

22-rails-validations/app/controllers/tacos_controller.rb
class TacosController < ApplicationController
  before_action :set_taco, only: [:show, :edit, :update, :destroy]

  def index
    @tacos = Taco.all
  end

  def show
  end

  def new
    @ingredients = Ingredient.all
    @taco = Taco.new
    @taco.ingredients.build
  end

  def create
    @taco = Taco.new(taco_params)

    byebug
    if @taco.valid?
      @taco.save
      redirect_to tacos_path
    else
      @ingredients = Ingredient.all
      render :new
    end
    # what about new ingredients?
  end

  def edit
    @ingredients = Ingredient.all
  end

  def update
    # update and validate taco
    # add and validate ingredients
    redirect_to taco_path(taco)
  end

  def destroy
    @taco.destroy
    redirect_to tacos_path
  end

  private
  def set_taco
    @taco = Taco.find(params[:id])
  end

  def taco_params
    params.require(:taco).permit(:name, ingredient_ids: [])
  end

  def ingredient_params
    # how are you getting your new ingredients
  end
end

22-rails-validations/app/helpers/tacos_helper.rb
module TacosHelper
end

22-rails-validations/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TacoTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

22-rails-validations/app/views/tacos/edit.erb
<!-- this is the exact same form from our new.erb. WAT???? -->
<%= form_for @taco do |f| %>
  Taco <%= f.label :name  %>
  <%= f.text_field :name %>
  <div class="">
    <%= f.collection_check_boxes(:ingredient_ids, @ingredients, :id, :name, {}, {style: 'margin-left:20px', class: 'niky-rules'}) %>
  </div>

  <%= f.fields_for :ingredients do |ingredient| %>
    <div class="">
      <h3>New Ingredient</h3>
      <%= ingredient.label :name%>
      <%= ingredient.text_field :name %>
      <%= ingredient.label :calories %>
      <%= ingredient.number_field :calories %>
    </div>
   <% end %>

<div class="">
  <%= f.submit %>
</div>
<% end %>

22-rails-validations/app/views/tacos/index.erb
<ol>
  <% @tacos.each do |taco| %>
    <li>
      <!-- <a href='/tacos/<%= taco.id %>'>
        <%= taco.name %>
      </a> -->
      <!-- <a href='<%= taco_path(taco) %>'>
        <%= taco.name %>
      </a> -->

      <!--  Link to generates an 'a' tag like the above-->
      <%= link_to taco.name, taco_path(taco)  %>
    </li>
  <% end %>
</ol>

22-rails-validations/app/views/tacos/new.erb
<% if !@taco.errors.empty? %>
<ul>
  <% @taco.errors.full_messages.each do |message| %>
  <li style='color:red'>
    <%= message %>
  </li>
  <% end %>
</ul>
<% end %>
<%= form_for @taco do |f| %>
  Taco <%= f.label :name  %>
  <%= f.text_field :name %>
  <div class="">
    <%= f.collection_check_boxes(:ingredient_ids, @ingredients, :id, :name, {}, {style: 'margin-left:20px', class: 'niky-rules'}) %>
  </div>

  <%= f.fields_for :ingredients do |ingredient| %>
    <div class="">
      <h3>New Ingredient</h3>
      <%= ingredient.label :name%>
      <%= ingredient.text_field :name %>
      <%= ingredient.label :calories %>
      <%= ingredient.number_field :calories %>
    </div>
   <% end %>

<div class="">
  <%= f.submit %>
</div>
<% end %>

22-rails-validations/app/views/tacos/show.erb
<h3>
  <%= @taco.name %>
</h3>
<ul>
  <% @taco.ingredients.each do |ingredient| %>
  <li>
    <%= ingredient.name %>: <%= ingredient.calories %>
  </li>
  <% end %>
</ul>
<button><%= link_to('Edit Taco', edit_taco_path, {method: :get}) %></button>
<%= button_to('Delete Taco', {action: 'destroy', id: @taco.id}, {method: :delete}) %>